<script src="./js/vendor/jquery/jquery-3.7.1.min.js"></script>
<script src="./js/vendor/bootstrap/bootstrap.bundle.min.js"></script>
<script src="./js/vendor/fontawesome/all.min.js"></script>
<script src="./js/vendor/gsap/gsap.min.js"></script>
<script src="./js/vendor/gsap/SplitText.min.js"></script>
<script src="./js/vendor/gsap/ScrollTrigger.js"></script>
<script src="./js/vendor/fastdom/fastdom.min.js"></script>
<script src="./js/vendor/flickity/flickity.pkgd.min.js"></script>
<script src="./js/vendor/flickity/flickity-fade.min.js"></script>
<script src="./js/vendor/lity/lity.min.js"></script>
<script src="./js/vendor/fresco/fresco.js"></script>
<script src="./js/vendor/fontfaceobserver/fontfaceobserver.js"></script>
<script src="./js/vendor/liquid/liquid-gdpr.min.js"></script>
<script src="./js/vendor/liquid/liquid-ajax-contact-form.min.js"></script>
<script src="./js/vendor/liquid/theme.min.js"></script>
<script src="<?php echo $final_js; ?>"></script>
